# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8753264008daeaf5b3f4c8346e9ce7046c3f70f3bafef62a7e43cf7b863269bf69ea82b133ac2f7e4bfc95d9e0d627c2546c836073040a9735df44c1087e74

test:
  secret_key_base: 281673e810333df667c418b942bbd5ece739b214c42f5f5146233be57929eb758af8539bc937497b55cf1720e4d97c12b16657b76c7bd79d9edd93e3fb7df920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
